# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# If you find yourself editing this file very often, consider using Jekyll's data files
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Johannes Wahle
name: Johannes Wahle
email: johannes@jowahle.de
logo: "/assets/images/JohannesWahle.jpg"
description: >-
  Johannes Wahle blogging about quality in software and efficient software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jowahle.de/" # the base hostname and protocol for your site, e.g. http://example.com
repository: "JWahle/jwahle.github.io"
github_username: JWahle

locale: "en-US"
remote_theme: mmistakes/minimal-mistakes@4.27.1 # https://mmistakes.github.io/minimal-mistakes/
# Configuration: https://mmistakes.github.io/minimal-mistakes/docs/configuration/
minimal_mistakes_skin: dark

# Search
search: true
lunr:
  search_within_pages: true

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

include:
  - _pages

exclude:
  - .idea
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/JWahle"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/johannes.wahle"

comments:
  provider: "giscus"
  giscus:
    repo_id: "MDEwOlJlcG9zaXRvcnkzNjk0OTA0NTQ=" # Shown during giscus setup at https://giscus.app
    category_name: "Comments" # Full-text name of the category
    category_id: "DIC_kwDOFgX6Fs4CttZF" # Shown during giscus setup at https://giscus.app
    discussion_term: "pathname" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled: "1" # '1' for enabled (default), '0' for disabled
    theme: "dark" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-QZ6E61L3TD"
    anonymize_ip: true # default
