# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
# If you find yourself editing this file very often, consider using Jekyll's data files
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Johannes Wahle
name: Johannes Wahle
email: johannes@jowahle.de
logo: "/assets/images/JohannesWahle.jpg"
description: >-
  Johannes Wahle blogging about quality in software and efficient software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.jowahle.de/" # the base hostname and protocol for your site, e.g. http://example.com
repository: "JWahle/jwahle.github.io"
github_username: JWahle

locale: "en-US"
theme: minimal-mistakes-jekyll # https://mmistakes.github.io/minimal-mistakes/
minimal_mistakes_skin: dark

plugins:
  - jekyll-feed

include:
  - _pages

exclude:
  - .idea
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
